#!/bin/bash

# 📱 Frontend Development Workflow
# Visual guide to working on the frontend

echo "
╔════════════════════════════════════════════════════════════════╗
║         🎨 FRONTEND DEVELOPMENT WORKFLOW                       ║
║     How to Work on React Frontend                             ║
╚════════════════════════════════════════════════════════════════╝
"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 1: Start Backend (Terminal 1)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ cd backend"
echo "  $ npm run dev"
echo ""
echo "  ✅ You should see:"
echo "     Server running on http://localhost:4000"
echo "     Listening for requests..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 STEP 2: Start Frontend (Terminal 2)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ cd frontend"
echo "  $ npm run dev"
echo ""
echo "  ✅ You should see:"
echo "     VITE v5.0.8 ready in 300 ms"
echo "     Local: http://localhost:3000"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 STEP 3: Open Browser"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Open: http://localhost:3000"
echo ""
echo "  You should see:"
echo "  ┌────────────────────────────────────────────┐"
echo "  │  🎯 RFP Management System                  │"
echo "  │  ├─ + Create RFP                          │"
echo "  │  ├─ Vendor Management                     │"
echo "  │  └─ [RFP Cards displayed here]            │"
echo "  └────────────────────────────────────────────┘"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🛠️  FILE STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  frontend/src/"
echo "  ├── main.tsx              ← React entry point (don't touch)"
echo "  ├── App.tsx               ← Page routing (edit here to add pages)"
echo "  ├── api.ts                ← API functions (edit here to add APIs)"
echo "  ├── index.css             ← Global styles (edit here for design)"
echo "  └── pages/"
echo "      ├── Dashboard.tsx     ← Shows RFPs (MODIFY)"
echo "      ├── CreateRFP.tsx     ← Create form (MODIFY)"
echo "      ├── Vendors.tsx       ← Manage vendors (MODIFY)"
echo "      └── RFPDetail.tsx     ← View & compare (MODIFY)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 COMMON TASKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  1️⃣  CHANGE COLORS"
echo "     File: frontend/src/index.css"
echo "     Find: --primary, --secondary, etc."
echo "     Action: Edit the color values"
echo ""

echo "  2️⃣  ADD A BUTTON"
echo "     File: Any page in frontend/src/pages/"
echo "     Copy: <button className=\"btn btn-primary\">...</button>"
echo "     Paste: Where you want it"
echo ""

echo "  3️⃣  ADD FORM FIELD"
echo "     File: frontend/src/pages/CreateRFP.tsx"
echo "     Copy: <input value={field} onChange={(e) => setField(e.target.value)} />"
echo "     Add: To your form"
echo ""

echo "  4️⃣  CALL BACKEND API"
echo "     File 1: frontend/src/api.ts"
echo "     Add: export const myAPI = { getData: async () => {...} };"
echo "     File 2: Any page"
echo "     Use: const data = await myAPI.getData();"
echo ""

echo "  5️⃣  SHOW ERROR MESSAGE"
echo "     Add: const [error, setError] = useState(null);"
echo "     In catch: setError('Error text');"
echo "     Display: {error && <div className=\"error-message\">{error}</div>}"
echo ""

echo "  6️⃣  SHOW LOADING STATE"
echo "     Add: const [loading, setLoading] = useState(false);"
echo "     Show: <button disabled={loading}>{loading ? '...' : 'Submit'}</button>"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 DEBUGGING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  When something breaks:"
echo ""
echo "  ✓ Check 1: Backend running?"
echo "    → Terminal 1 should show 'Server running on http://localhost:4000'"
echo ""
echo "  ✓ Check 2: Frontend running?"
echo "    → Terminal 2 should show 'VITE ready in...' and http://localhost:3000"
echo ""
echo "  ✓ Check 3: Browser console errors?"
echo "    → Open DevTools: F12 (Windows) or Cmd+Option+I (Mac)"
echo "    → Click Console tab"
echo "    → Look for red error messages"
echo ""
echo "  ✓ Check 4: API working?"
echo "    → Open DevTools: F12"
echo "    → Click Network tab"
echo "    → Make an API call (e.g., Create RFP)"
echo "    → See the request and response"
echo ""
echo "  ✓ Check 5: Type errors?"
echo "    → Terminal 2 might show TypeScript errors"
echo "    → Read the error message"
echo "    → Fix the issue and save"
echo "    → Page hot-reloads automatically"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ HOT RELOADING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✨ Magic Feature: Auto Reload"
echo ""
echo "  1. Make a change in any .tsx or .css file"
echo "  2. Save the file (Ctrl+S or Cmd+S)"
echo "  3. Browser automatically reloads!"
echo ""
echo "  No need to refresh manually. Vite does it for you."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  📄 FRONTEND_GUIDE.md          ← Full guide (read this!)"
echo "  📄 FRONTEND_QUICK_REF.md      ← Quick reference"
echo "  📄 README.md                  ← Project overview"
echo "  📄 ARCHITECTURE.md            ← System design"
echo "  🎬 DEMO_GUIDE.md              ← Demo walkthrough"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 TYPICAL WORKFLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  Morning:"
echo "  ┌─ Terminal 1: cd backend && npm run dev"
echo "  ├─ Terminal 2: cd frontend && npm run dev"
echo "  └─ Browser: Open http://localhost:3000"
echo ""

echo "  During the day:"
echo "  ┌─ Edit frontend/src/pages/Dashboard.tsx"
echo "  ├─ Save (Ctrl+S)"
echo "  ├─ Browser auto-reloads"
echo "  ├─ See your changes immediately"
echo "  ├─ Check DevTools if something breaks"
echo "  └─ Git commit when happy"
echo ""

echo "  Common Git commands:"
echo "  $ git status           ← See what changed"
echo "  $ git add .            ← Stage all changes"
echo "  $ git commit -m \"Done\" ← Commit"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 YOUR TASK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  Pick ONE of these to start:"
echo ""
echo "  1. Change button color in Dashboard"
echo "     → Edit frontend/src/index.css"
echo "     → Find '.btn-primary' and change 'background: #007bff;'"
echo "     → Save and see it change in browser"
echo ""

echo "  2. Add a new field to Vendors form"
echo "     → Edit frontend/src/pages/Vendors.tsx"
echo "     → Add a new input field"
echo "     → Save and test it"
echo ""

echo "  3. Add an example text to CreateRFP"
echo "     → Edit frontend/src/pages/CreateRFP.tsx"
echo "     → Add more <div className=\"example\"> sections"
echo "     → Save and see them appear"
echo ""

echo "  4. Call a new API endpoint"
echo "     → Edit frontend/src/api.ts"
echo "     → Add a new function"
echo "     → Use it in a component"
echo "     → Test with DevTools Network tab"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📖 Read FRONTEND_GUIDE.md for detailed examples!"
echo "⚡ Read FRONTEND_QUICK_REF.md for quick commands!"
echo ""
echo "Ready? Start working! 🎨✨"
echo ""
